# Generated by Django 3.1.5 on 2021-12-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('quote', models.TextField(max_length=550)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
