# Generated by Django 3.1.5 on 2021-12-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('AKL', 'Auckland'), ('WLG', 'Wellington'), ('CHC', 'Christchurch'), ('QT', 'Queenstown')], max_length=10)),
                ('quote', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
