# Generated by Django 3.2.8 on 2021-12-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20211210_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('Auckland, New Zealand', 'AKL'), ('Wellington, New Zealand', 'WLG'), ('Christchurch, New Zealand', 'CHC'), ('Queenstown, New Zealand', 'QT')], max_length=50),
        ),
    ]
